### ISSUE TITLE
Sending keepalive message will throw an exception

### ISSUE THREAD

**Issue by sTeaPig** [jimm98y/SharpRTSPtoWebRTC#1]
this line of code
https://github.com/jimm98y/SharpRTSPtoWebRTC/blob/8d1a868490c406de40974a71bdd122573783d5d1/src/SharpRTSPtoWebRTC/RTSP/RTSPClient.cs#L700
when _keepaliveTimer.Elapsed is triggered, will throw System.NullReferenceException: 'Object reference not set to an instance of an object.'
Rtsp.Messages.RtspResponse.OriginalRequest.get return null。

**Comment by jimm98y** [comment]
Thank you very much for reporting it! I could not reproduce the issue with my streams, but looking at the code it looks valid. Should be fixed.
