### ISSUE TITLE
Unsupported video codec  H265

### ISSUE THREAD

**Issue by canyanol650** [jimm98y/SharpRTSPtoWebRTC#3]
![image](https://github.com/jimm98y/SharpRTSPtoWebRTC/assets/42194280/c8c063bc-7d7f-408c-a5e9-ddd32d902697)

**Comment by jimm98y** [comment]
You have to use Safari web browser on Mac OS and enable the experimental h265 WebRTC support in feature flags. Then it will work, so I believe the condition is correct.
