### ISSUE TITLE
Audio Payload Type PCMU

### ISSUE THREAD

**Issue by ChristianKnoblauch** [jimm98y/SharpRTSPtoWebRTC#6]
Inside the RTSPtoWebRTCProxy constructor, seeting the AudioCodecEnum will never set PCMU since this is guarded by
             
if (AudioType > 0)
{
    AudioCodecEnum = GetAudioCodec(AudioCodec);
} 

where PCMU would be AudioType = 0

if (AudioType > -1) should work i guess...

**Comment by jimm98y** [comment]
You are right, it seems to be the case. I have no PCMU stream to test this, but it should be fixed now.
